spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/airbng?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ${DB_LOCAL_PASSWD}
  data:
    redis:
      host: ${REDIS_HOST}
      username: ${REDIS_USERNAME}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  devtools:
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.web : DEBUG
  org.springframework.web.socket : DEBUG
  org.apache.kafka: DEBUG
  org.springframework.kafka:
  org.springframework.cache: DEBUG

