server:
  port: 9000
  servlet:
    context-path: /AirBnG
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  profiles:
    active: ${PROFILE}
  application:
    name: airbng
  jwt:
    secret : ${JWT_SECRET}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region: ${AWS_REGION}
    accessKey: ${AWS_ACCESSKEY}
    secretKey: ${AWS_SECRETKEY}
springdoc:
  packages-to-scan: com.airbng
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
image :
  default-url: ${DEFAULT_IMAGE_URL}